### ISSUE TITLE
Does the M calculate correct?

### ISSUE THREAD

**Issue by elct9620** [grempe/sirp#9]
I am trying to use Golang (wams) and JavaScript as the client to verify their session, but it seems there has some problem with the `M` calculation.

According to the design, the M will include the `H(N) xor H(g)` and `H(I)` and `s`

```
User -> Host:  M = H(H(N) xor H(g), H(I), s, A, B, K)
Host -> User:  H(A, M, K)
```

But the source code doesn't include it, the `#calc_M` only gives the `H(A, B, K)`

https://github.com/grempe/sirp/blob/b8d903fcdcd8eabae7a8479a393d52852a4e417e/lib/sirp/sirp.rb#L150-L156

In my memory, the `H(A, B, K)` is valid but not for SRP6a, therefore the JavaScript or Golang library cannot calculate the correct value for SIRP.

**Comment by grempe** [comment]
To start, this library is only lightly maintained at this point and the use of Golang or other JavaScript implementations is not supported outside of the tested JS client. Since I have not used or looked at this code in a while it took me a little digging to understand your issue. :-)

I think perhaps you are mixing a couple of concepts. The `Host -> User:  H(A, M, K)` is provided by the host to allow the client to verify. It is implemented in https://github.com/grempe/sirp/blob/7337274f46d279403d7c76ce722fccb29f104dae/lib/sirp/sirp.rb#L159 and not the code you linked to.

This lib does not implement the `User -> Host:  M = H(H(N) xor H(g), H(I), s, A, B, K)` verification step.

The client expects to receive @h_amk as returned by this step and it verifies that locally:

https://github.com/grempe/sirp/blob/6c32b2679af7d9cb9255d9423bed9bf242e1fa8e/lib/sirp/verifier.rb#L123

The `M` used in constructing that response is generated by the code you linked to.

Hope that helps.

**Comment by elct9620** [comment]
The client expects to receive the `HAMK` from the server, but the server and client both calc the `M` in their side to verify it.

The source code I point out the `calc_M` seems not to match the document `User -> Host:  M = H(H(N) xor H(g), H(I), s, A, B, K)`

It only creates the `H(A, B, K)` instead of `H(H(N) xor H(g), H(I), s, A, B, K)`. This gem works correctly because the server and client use the same `calc_M` method to calculate it.

But it seems not to match the document `User -> Host:  M = H(H(N) xor H(g), H(I), s, A, B, K)` that other library cannot have the same value for this gem.

I am not sure does the SRP-6a have a different calculate in this case, but another Ruby library I found also use `H(H(N) xor H(g), H(I), s, A, B, K)` instead of `H(A, B, K)`

https://github.com/unlightcpa/Unlight/blob/master/app/server/src/net/srp.rb#L54
